

env_name: CartPole-v1

# Model config
vf_share_layers: true
hidden_size: 128
num_hidden_layers: 2
fcnet_activation: "relu"

# Training config
learning_rate: 0.0003
gamma: 0.99
train_batch_size_per_learner: 128
num_epochs: 5

use_gae: true
use_critic: true
lambda_: 0.95
vf_loss_coeff: 0.5
entropy_coeff: 0.01
clip_param: 0.2
vf_clip_param: 10.0
grad_clip: 0.5

seed: 0

# Evaluation config
evaluation_interval: 100
evaluation_duration: 10
evaluation_duration_unit: "episodes"

max_timesteps: 30000