# config/config.yaml
defaults:
    - _self_

total_timesteps: 300000
log_dir: logs/
model_dir: model/
env_id: LunarLander-v3
n_envs: 8

ppo:
    learning_rate: 0.0003
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    training_gravity: -5
